apiVersion: v1
kind: Secret
metadata:
  name: camunda7-db-secret
  namespace: camunda7
type: Opaque
# Store actual values in Azure Key Vault and sync via CSI driver or
# replace with base64-encoded values:  echo -n 'value' | base64
stringData:
  # db-username: camunda_admin
  # db-password: Mnbzxc@123$
  # camunda-admin-password: Camunda2024!
  db-username: camunda
  db-password: camunda
  camunda-admin-password: camunda
  # db-username: camunda_admin
  # db-password: camunda_admin
  # camunda-admin-password: camunda_admin