apiVersion: v1
kind: Service
metadata:
  name: camunda7-svc
  namespace: camunda7
  labels:
    app: camunda7
spec:
  selector:
    app: camunda7
  ports:
    - name: http
      port: 80
      targetPort: 8081
  type: ClusterIP
